language: generic
sudo: required
services:
  - docker

before_install:
  # Build development image of the client project
  - docker build -t agustinmag/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run the test of the client project
  - docker run -e CI=true agustinmag/react-test npm test

after_success:
  # Build production images of each project
  - docker build -t agustinmag/multi-client ./client
  - docker build -t agustinmag/multi-nginx ./nginx
  - docker build -t agustinmag/multi-server ./server
  - docker build -t agustinmag/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push agustinmag/multi-client
  - docker push agustinmag/multi-nginx
  - docker push agustinmag/multi-server
  - docker push agustinmag/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-577354254112
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY